#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

# Some stuff needed for Hyprland
export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER_ALLOW_SOFTWARE=1

# Some stuff to make Dolphin display icons
export QT_QPA_PLATFORMTHEME=qt5ct

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Exports for SW development
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
export C_COMPILER=${CC}
export CXX_COMPILER=${CXX}
export CMAKE_C_COMPILER=${CC}
export CMAKE_CXX_COMPILER=${CXX}
export BOOST_ROOT=$HOME/tools/boost
export DEVELOP=$HOME/dev/cpp
export GOPATH=$HOME/.local/share/go

# Add necessary locations to PATH
export PATH=$HOME/.fnm:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/share/neovim/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$HOME/.local/share/pipx/venvs/hexlet-code/bin:$PATH

#export PATH="$PATH:./node_modules/.bin"
eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
        . "$HOME/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

